#!/bin/bash

# Configurações do diretório base
DIRECTORY_BASE=$(realpath `dirname $0`)
PACKAGE_MODULE_MAIN="modules.main"

# Importa as Configurações
source ${DIRECTORY_BASE}/config/app.ini
source ${DIRECTORY_BASE}/config/bitbucket.ini
source ${DIRECTORY_BASE}/config/mvn.ini
source ${DIRECTORY_BASE}/config/svn.ini
source ${DIRECTORY_BASE}/config/zsh.ini

# Importa o modulo PostInstall
source ${DIRECTORY_BASE}/modules/postinstall/zsh
source ${DIRECTORY_BASE}/modules/postinstall/bash
source ${DIRECTORY_BASE}/modules/postinstall/packages
source ${DIRECTORY_BASE}/modules/postinstall/dotfiles

# Importa o modulo Sistema
source ${DIRECTORY_BASE}/modules/system/progress_bar
source ${DIRECTORY_BASE}/modules/system/os

# Importa o modulo Utilidade
source ${DIRECTORY_BASE}/modules/util/bitbucket
source ${DIRECTORY_BASE}/modules/util/mvn

# Seta permissão de execução nos binários dos módulos
function permissions(){
  chmod u+x ${DIRECTORY_BASE}/modules/*/*
}

# Inicia o fluxo de instalação e configuração
function postinstall(){
    PACKAGE_MODULE_MAIN_POST_INSTALL="${PACKAGE_MODULE_MAIN}.${FUNCNAME[0]}"
    basic.packages
    repositories
    packages
    echo -ne "[INFO $(date "+%Y-%m-%d %H:%M:%S")] - ${PACKAGE_MODULE_MAIN_POST_INSTALL} - Voce tem interesse em Configurar o Zsh? (Ss/Nn) " && read OPTS
    if [[ $OPTS =~ ^[YysS]$ ]]; then
      zsh
      zsh.configure
      zshrc
      copyfiles
      symboliclinks
    else
      bash
      copyfiles
      symboliclinks
      echo -ne "[INFO $(date "+%Y-%m-%d %H:%M:%S")] - ${PACKAGE_MODULE_MAIN_POST_INSTALL} - fim da execucao"
      exit
    fi
}

# Funções que podem ser acionadas pelo script main
case $1 in
  -permissions) permissions ;;
  -pinstall) postinstall ;;
  -supdate) supdate ;;
  -sclone) sclone ;;
  -bclone) bclone ;;
  -bupdate) bupdate ;;
  -updateos) updateos ;;
  -build) run.builds ;;
  *) echo "Opcao invalida utilize: -pinstall, -supdate, -sclone, -bupdate, -bclone, -updateos, -build"
    exit 1
    ;;
esac


